### PR TITLE
code changes to convert all instances of / to ~ (for AS3 declarations)

### PR DESCRIPTION
**Pull request by aknot242**
Since there may be more than 2 instances of the '/' character in a BIG-IP path (such as in an AS3 declaration), all need to be replaced with '~'. Created path conversion function, and refactored to it.

### CODE REVIEW

**Comment by aknot242** [comment]
Thanks Chad! @cjenison

**Comment by cjenison** [comment]
How’d you get a notification?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by aknot242** [comment]
Pardon? How did I find your solution, or how'd I determine the AS3 thing?

**Comment by cjenison** [comment]
Oh I see what’s going on. You just commented. My bad. Thought all of a sudden GitHub was generating alerts for some reason.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Pull request merged**
